import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Flex, Box, Heading } from '@chakra-ui/react'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <Flex 
          mt='5' 
          alignItems="center" 
          justifyContent='right' 
          bg='' 
          w='90vw' 
          p='4' 
          color='white' 
          rounded={10}>

          <Heading 
            letterSpacing='.1em' 
            fontFamily='Playfair_Display'
            fontWeight='400'
            
            fontSize='24'
            >

              About \ Work \ Contact

          </Heading>

        </Flex>
        
      </main>
    </div>
  )
}
